"""добавилено отображеные опубликованности новости

Revision ID: 89142ea66139
Revises: 
Create Date: 2021-04-11 20:33:07.625205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89142ea66139'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_published', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_published')
    # ### end Alembic commands ###
